bitvector: bitvector.c
	gcc -Wall -Werror -pedantic -std=gnu99 bitvector.c -o bitvector

sorter: sorter.c
	gcc -Wall -Werror -pedantic -std=gnu99 sorter.c -o sorter

clean:
	rm -f bitvector sorter *.o
